@CharacterHitpointService_HostAddress = http://localhost:5102

POST {{HitpointService_HostAddress}}/damage/
Accept: application/json
Content-Type: application/json

{
  "characterId": "briv",
  "damage": 10,
  "type": "acid"
}

###
