@CharacterHitpointService_HostAddress = http://localhost:5102

POST {{CharacterHitpointService_HostAddress}}/character/briv/damage/
Accept: application/json
Content-Type: application/json

{
  "amount": 9,
  "type": "slashing"
}

###

POST {{CharacterHitpointService_HostAddress}}/character/briv/heal/
Accept: application/json
Content-Type: application/json

{
  "amount": 10
}

###

POST {{CharacterHitpointService_HostAddress}}/character/briv/addTemporaryHitpoints/
Accept: application/json
Content-Type: application/json

{
  "amount": 10
}
